language: python
python:
    - "3.6"
    - "pypy3.5"
install:
    - pip install -r requirements.txt
    - python pyrefo/pyrefo_build.py
    - pip install codecov
script:
    - pytest
notifications:
    email: false
after_success:
    - codecov
